env:
  global:
  - TERM=dumb

language: java
jdk:
  - oraclejdk8


# Workaround for https://github.com/travis-ci/travis-ci/issues/5227
# Buffer overflow in Java_java_net_Inet4AddressImpl_getLocalHostName
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

branches:
  only:
    - master
install: /bin/true
script: "mvn -q clean install"
notifications:
  email:
    recipients:
      - sandro.coelho@ice.ufjf.br
      - dojcinovski.milan@gmail.com
    on_success: change
    on_failure: change
